@host = http://localhost:5089

POST {{host}}/api/setup/admin
Content-Type: application/json

{
  "nombre":   "Isaac",
  "apellido": "Acevedo",
  "email":    "isaac.acevedor1610@gmail.com",
  "password": "Admin1234",
  "role":     "Admin"
}

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email":    "admin@instituto.edu.ar",
  "password": "Admin1234!"
}

POST {{host}}/api/administradores
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "nombre":      "Secretaría",
  "apellido":    "Instituto",
  "email":       "secretaria@instituto.edu.ar",
  "role":        "Secretaria",
  "passwordTemp": "Secretaria123!"
}


GET {{host}}/api/profesores
Authorization: Bearer TU_TOKEN_AQUI

GET {{host}}/api/carreras

POST {{host}}/api/carreras
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "nombre": "Tecnicatura en Sistemas",
  "duracionAnios": 3,
  "turno": "Noche",
  "modalidad": "Presencial",
  "horario": "18:00 a 22:00",
  "estado": "Activa"
}

GET {{host}}/api/alumnos
Authorization: Bearer TU_TOKEN_AQUI

GET {{host}}/api/listado
Authorization: Bearer TU_TOKEN_AQUI

